export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"
//// Register
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"
//// getProfile
export const USER_DETAILED_REQUEST = "USER_DETAILED_REQUEST"
export const USER_DETAILED_SUCCESS = "USER_DETAILED_SUCCESS"
export const USER_DETAILED_FAIL = "USER_DETAILED_FAIL"
export const USER_DETAILED_RESET = "USER_DETAILED_RESET"

//// updateProfile
export const USER_UPDATE_REQUEST = "USER_DETAILED_REQUEST"
export const USER_UPDATE_SUCCESS = "USER_DETAILED_SUCCESS"
export const USER_UPDATE_FAIL = "USER_DETAILED_FAIL"



